export function getCalculatorDom() {
  const doc = document;
  const form = doc.getElementById("storageForm");
  if (!form) {
    return { form: null };
  }

  const continueBtn = doc.getElementById("continueBtn");

  return {
    form,
    toggleButtons: doc.querySelectorAll(".storage-toggle-btn"),
    hiddenInput: doc.getElementById("storageType"),
    errorText: form.querySelector(".storage-form__error-text"),
    panel: doc.getElementById("formPanel"),
    messages: doc.querySelector(".storage-form__messages"),
    initialView: doc.getElementById("initialView"),
    expandedView: doc.getElementById("expandedView"),
    sharedToggle: doc.getElementById("sharedToggle"),
    toggleExpandedSlot: doc.getElementById("toggleExpandedSlot"),
    backBtn: doc.querySelector(".calc-back-btn"),
    currentPostcodeInput: doc.getElementById("postcode"),
    mainAutocomplete: doc.querySelector(".main-autocomplete"),
    postcodePill: doc.getElementById("postcodePill"),
    postcodeSearchMode: doc.getElementById("postcodeSearchMode"),
    postcodeText: doc.querySelector(".calc-postcode-text"),
    editInput: doc.querySelector(".calc-edit-input"),
    editAutocomplete: doc.querySelector(".edit-autocomplete"),
    calcBoxesView: doc.getElementById("calcBoxesView"),
    calcFurnitureView: doc.getElementById("calcFurnitureView"),
    desktopStepBackBtn: doc.getElementById("desktopStepBackBtn"),
    mobileStepBackBtn: doc.getElementById("mobileStepBackBtn"),
    continueBtn,
    mobileContinueBtn: doc.getElementById("mobileContinueBtn"),
    continueBtnText: continueBtn?.querySelector(".btn-text-content"),
    continueBtnSpinner: continueBtn?.querySelector(".btn-spinner"),
    contactName: doc.getElementById("contactName"),
    contactPhone: doc.getElementById("contactPhone"),
    contactEmail: doc.getElementById("contactEmail"),
    contactNameError: doc.getElementById("contactNameError"),
    contactPhoneError: doc.getElementById("contactPhoneError"),
    contactEmailError: doc.getElementById("contactEmailError"),
    termsError: doc.getElementById("termsError"),
    termsCheckbox: doc.getElementById("termsCheckbox"),
    sidebarTermsBox: doc.getElementById("sidebarTermsBox"),
    checkoutSummaryBox: doc.getElementById("checkoutSummaryBox"),
    dateModal: doc.getElementById("confirmDateModal"),
    exitModal: doc.getElementById("exitWarningModal"),
    switchModal: doc.getElementById("switchTypeModal"),
    btnCancelSwitch: doc.getElementById("btnCancelSwitch"),
    btnConfirmSwitch: doc.getElementById("btnConfirmSwitch"),
    modalBtnChange: doc.getElementById("modalBtnChange"),
    modalBtnConfirm: doc.getElementById("modalBtnConfirm"),
    btnOpenCalendar: doc.getElementById("btnOpenCalendar"),
    btnExitSave: doc.getElementById("btnExitSave"),
    btnExitDiscard: doc.getElementById("btnExitDiscard"),
    btnExitCancel: doc.getElementById("btnExitCancel"),
    step1Container: doc.getElementById("step1Container"),
    step2Container: doc.getElementById("step2Container"),
    step3Container: doc.getElementById("step3Container"),
    step4Container: doc.getElementById("step4Container"),
    calcSidebar: doc.getElementById("calcSidebar"),
    panelTopBar: doc.getElementById("panelTopBar"),
    calcStepsHeader: doc.getElementById("calcStepsHeader"),
    calcLayoutArea: doc.getElementById("calcLayoutArea"),
    boxesItemsList: doc.getElementById("boxesItemsList"),
    unitsListContainer: doc.getElementById("unitsListContainer"),
    durationMinus: doc.getElementById("durationMinus"),
    durationPlus: doc.getElementById("durationPlus"),
    durationInput: doc.getElementById("durationInput"),
    rollingPlanToggle: doc.getElementById("rollingPlanToggle"),
    durationPromo: doc.getElementById("durationPromo"),
    rollingText: doc.getElementById("rollingText"),
    billingNote: doc.getElementById("billingNote"),
    durationMinusFurn: doc.getElementById("durationMinusFurn"),
    durationPlusFurn: doc.getElementById("durationPlusFurn"),
    durationInputFurn: doc.getElementById("durationInputFurn"),
    rollingPlanToggleFurn: doc.getElementById("rollingPlanToggleFurn"),
    durationPromoFurn: doc.getElementById("durationPromoFurn"),
    rollingTextFurn: doc.getElementById("rollingTextFurn"),
    billingNoteFurn: doc.getElementById("billingNoteFurn"),
    qtyWrapFurn: doc.getElementById("qtyWrapFurn"),
    summaryItems: doc.getElementById("summaryItems"),
    summarySubtotal: doc.getElementById("summarySubtotal"),
    summaryTotal: doc.getElementById("summaryTotal"),
    mobileSummaryTotal: doc.getElementById("mobileSummaryTotal"),
    summaryCard: doc.getElementById("summaryCard"),
    summaryMobileToggle: doc.getElementById("summaryMobileToggle"),
    durationQtyBoxes: doc.querySelector("#calcBoxesView .duration-qty"),
  };
}
